const fallback = {
  accept: 'Принять',
  add: 'Добавить',
  adult_content_warning: 'Изображение может содержать контент 18+',
  apply: 'Применить',
  blockedaccdesc: 'Аккаунт заблокирован',
  blockedgroupdesc: 'Сообщество заблокировано',
  bookmarkadded: 'Добавлено в закладки',
  bookmarked: 'В закладках',
  bookmarkremoved: 'Удалено из закладок',
  candidimage: 'Откровенное изображение',
  cancel: 'Отменить',
  copylink: 'Скопировать ссылку',
  delete: 'Удалить',
  deletepost: 'Удалить пост',
  dialogblocked: 'Диалог заблокирован',
  dialogcreated: 'Диалог создан',
  edit: 'Редактировать',
  editgroup: 'Редактировать сообщество',
  editgroupWARN: 'Будьте внимательны при изменении ссылки сообщества.',
  emptycomments: 'Комментариев пока нет',
  emptycommentsdesc: 'Будьте первым, кто что-то напишет.',
  errorhappend: 'Произошла ошибка =(',
  follow: 'Подписаться',
  friends: 'Друзья',
  groupdesc: 'Описание сообщества',
  groupname: 'Название сообщества',
  groupnotfound: 'Сообщество не найдено',
  groups: 'Сообщества',
  home: 'Home',
  langname: 'en',
  less: 'Скрыть',
  linkcopied: 'Ссылка скопирована',
  linktogroup: 'Ссылка на сообщество',
  loading: 'Загрузка...',
  logintoreact: 'Войдите, чтобы взаимодействовать с публикациями',
  more: 'Подробнее',
  no: 'Нет',
  nomoreposts: 'Больше постов нет',
  noposts: 'Постов пока нет',
  nopostsdesc: 'У этого пользователя пока нет публикаций.',
  nosubscribersgr: 'Пока здесь нет подписчиков',
  officialgroups: 'Официальные сообщества',
  pagenotfound: 'Пользователь не найден',
  photo: 'Фото',
  postcomments: 'Комментарии',
  prohibitedgood: 'Запрещённый товар',
  propertyrights: 'Нарушение интеллектуальных прав',
  reallywantdeletepost: 'Вы действительно хотите удалить пост?',
  report: 'Пожаловаться',
  scam: 'Обман',
  share: 'Поделиться',
  somethingwrong: 'Что-то пошло не так',
  spam: 'Спам',
  subscribers: 'Подписчики',
  successGroupUpdate: 'Это успех! Все готово, проверяйте!',
  successProfileUpdate: 'Это успех! Все готово, проверяйте!',
  tbookmark: 'В закладки',
  tobookmark: 'В закладки',
  tobookmarks: 'В закладки',
  translate: 'Перевести',
  unfollow: 'Отписаться',
  updateprofilecover: 'Обновить обложку профиля',
  updateprofilepicture: 'Обновить фото профиля',
  uploadphoto: 'Выберите изображение',
  violence: 'Насилие и вражда',
  writecomment: 'Напишите комментарий',
  writetouser: 'Написать',
  yes: 'Да',
  all: 'Все',
  bookmarks: 'Закладки',
  feed: 'Лента',
  films: 'Фильмы',
  food: 'Еда',
  games: 'Игры',
  humor: 'Юмор',
  investment: 'Инвестиции',
  it: 'IT',
  music: 'Музыка',
  my: 'Моё',
  news: 'Новости',
  post: 'Пост',
  science: 'Наука',
  sport: 'Спорт',
  tourism: 'Туризм',
  postnotfound: 'Запись не найдена',
  choisetopic: 'Выберите тему',
  errorDescription: 'Попробуйте обновить страницу чуть позже.',
  max3photos: 'Можно загрузить не больше 3 фотографий',
  nopost: 'Запись не найдена',
  nopostdesc: 'Возможно, она была удалена или ссылка неверна.',
  notyourpost: 'Не ваша запись!',
  notyourpostdesc: 'Чужие записи нельзя изменять.',
  nowTyping: 'Печатается сейчас!',
  placeholderAuthor: 'Автор',
  placeholderContent: 'Текст поста',
  placeholderTag: 'Тема',
  placeholderTitle: 'Заголовок',
  poll: 'Опрос',
  postcontent: 'Содержимое поста',
  preview: 'Предпросмотр',
  save: 'Сохранить',
  saved: 'Изменения сохранены',
  title: 'Заголовок',
  uploadedcompl: 'Фотография загружена',
  uploading: 'Загружается...',
  video: 'Видео',
  waituntillphotouploaded: 'Подождите, пока фотография загрузится',
  frommyname: 'От моего имени',
  newpost: 'Новый пост',
  photosPlaceholder: 'Здесь появятся все загруженные фотографии.',
  publicpost: 'Опубликовать',
};

export type LangStrings = typeof fallback;

const CACHE_KEY = 'lang_cache';
const CACHE_DURATION = 5 * 60 * 1000; // 5 минут

export function getLangFromCache(): typeof fallback | null {
  if (typeof window === 'undefined') return null;

  try {
    const cached = window.localStorage.getItem(CACHE_KEY);
    if (!cached) return null;

    const { data, timestamp } = JSON.parse(cached) as {
      data: Partial<typeof fallback>;
      timestamp: number;
    };

    if (Date.now() - timestamp > CACHE_DURATION) {
      window.localStorage.removeItem(CACHE_KEY);
      return null;
    }

    return { ...fallback, ...data };
  } catch {
    return null;
  }
}

export function saveLangToCache(lang: Record<string, string>) {
  if (typeof window === 'undefined') return;

  try {
    window.localStorage.setItem(
      CACHE_KEY,
      JSON.stringify({ data: lang, timestamp: Date.now() }),
    );
  } catch {
    // Игнорируем ошибки кэширования
  }
}

export function useLangStrings(lang: Record<string, string> | null) {
  return {
    accept: lang?.accept ?? fallback.accept,
    add: lang?.add ?? fallback.add,
    adult_content_warning: lang?.adult_content_warning ?? fallback.adult_content_warning,
    apply: lang?.apply ?? fallback.apply,
    blockedaccdesc: lang?.blockedaccdesc ?? fallback.blockedaccdesc,
    blockedgroupdesc: lang?.blockedgroupdesc ?? fallback.blockedgroupdesc,
    bookmarkadded: lang?.bookmarkadded ?? fallback.bookmarkadded,
    bookmarked: lang?.bookmarked ?? fallback.bookmarked,
    bookmarkremoved: lang?.bookmarkremoved ?? fallback.bookmarkremoved,
    cancel: lang?.cancel ?? fallback.cancel,
    candidimage: lang?.candidimage ?? fallback.candidimage,
    copylink: lang?.copylink ?? fallback.copylink,
    delete: lang?.delete ?? fallback.delete,
    deletepost: lang?.deletepost ?? fallback.deletepost,
    dialogblocked: lang?.dialogblocked ?? fallback.dialogblocked,
    dialogcreated: lang?.dialogcreated ?? fallback.dialogcreated,
    edit: lang?.edit ?? fallback.edit,
    editgroup: lang?.editgroup ?? fallback.editgroup,
    editgroupWARN: lang?.editgroupWARN ?? fallback.editgroupWARN,
    emptycomments: lang?.emptycomments ?? fallback.emptycomments,
    emptycommentsdesc: lang?.emptycommentsdesc ?? fallback.emptycommentsdesc,
    errorhappend: lang?.errorhappend ?? fallback.errorhappend,
    follow: lang?.follow ?? fallback.follow,
    friends: lang?.friends ?? fallback.friends,
    groupdesc: lang?.groupdesc ?? fallback.groupdesc,
    groupname: lang?.groupname ?? fallback.groupname,
    groupnotfound: lang?.groupnotfound ?? fallback.groupnotfound,
    groups: lang?.groups ?? fallback.groups,
    home: lang?.Home ?? lang?.home ?? fallback.home,
    langname: lang?.langname ?? fallback.langname,
    less: lang?.less ?? fallback.less,
    linkcopied: lang?.linkcopied ?? fallback.linkcopied,
    linktogroup: lang?.linktogroup ?? fallback.linktogroup,
    loading: lang?.['loading...'] ?? fallback.loading,
    logintoreact: lang?.logintoreact ?? fallback.logintoreact,
    more: lang?.more ?? fallback.more,
    no: lang?.no ?? fallback.no,
    nomoreposts: lang?.nomoreposts ?? fallback.nomoreposts,
    noposts: lang?.noposts ?? fallback.noposts,
    nopostsdesc: lang?.nopostsdesc ?? fallback.nopostsdesc,
    nosubscribersgr: lang?.nosubscribersgr ?? fallback.nosubscribersgr,
    officialgroups: lang?.officialgroups ?? fallback.officialgroups,
    pagenotfound: lang?.pagenotfound ?? fallback.pagenotfound,
    photo: lang?.photo ?? fallback.photo,
    postcomments: lang?.postcomments ?? fallback.postcomments,
    prohibitedgood: lang?.prohibitedgood ?? fallback.prohibitedgood,
    propertyrights: lang?.propertyrights ?? fallback.propertyrights,
    reallywantdeletepost: lang?.reallywantdeletepost ?? fallback.reallywantdeletepost,
    report: lang?.report ?? fallback.report,
    scam: lang?.scam ?? fallback.scam,
    share: lang?.share ?? fallback.share,
    somethingwrong: lang?.somethingwrong ?? fallback.somethingwrong,
    spam: lang?.spam ?? fallback.spam,
    subscribers: lang?.subscribers ?? fallback.subscribers,
    successGroupUpdate: fallback.successGroupUpdate,
    successProfileUpdate: fallback.successProfileUpdate,
    tbookmark: lang?.tobookmark ?? fallback.tobookmark,
    tobookmarks: lang?.tobookmarks ?? fallback.tobookmarks,
    tobookmark: lang?.tobookmark ?? fallback.tobookmark,
    translate: lang?.translate ?? fallback.translate,
    unfollow: lang?.unfollow ?? fallback.unfollow,
    updateprofilecover: lang?.updateprofilecover ?? fallback.updateprofilecover,
    updateprofilepicture: lang?.updateprofilepicture ?? fallback.updateprofilepicture,
    uploadphoto: lang?.uploadphoto ?? lang?.photo ?? fallback.uploadphoto,
    violence: lang?.violence ?? fallback.violence,
    writecomment: lang?.writecomment ?? fallback.writecomment,
    writetouser: lang?.writetouser ?? fallback.writetouser,
    yes: lang?.yes ?? fallback.yes,
    all: lang?.all ?? fallback.all,
    bookmarks: lang?.bookmarks ?? fallback.bookmarks,
    feed: lang?.feed ?? fallback.feed,
    films: lang?.films ?? fallback.films,
    food: lang?.food ?? fallback.food,
    games: lang?.games ?? fallback.games,
    humor: lang?.humor ?? fallback.humor,
    investment: lang?.investment ?? fallback.investment,
    it: lang?.it ?? fallback.it,
    music: lang?.music ?? fallback.music,
    my: lang?.my ?? fallback.my,
    news: lang?.news ?? fallback.news,
    post: lang?.post ?? fallback.post,
    science: lang?.science ?? fallback.science,
    sport: lang?.sport ?? fallback.sport,
    tourism: lang?.tourism ?? fallback.tourism,
    postnotfound: lang?.postnotfound ?? fallback.postnotfound,
    choisetopic: lang?.choisetopic ?? fallback.choisetopic,
    errorDescription: lang?.errorDescription ?? fallback.errorDescription,
    max3photos: lang?.max3photos ?? fallback.max3photos,
    nopost: lang?.nopost ?? fallback.nopost,
    nopostdesc: lang?.nopostdesc ?? fallback.nopostdesc,
    notyourpost: lang?.notyourpost ?? fallback.notyourpost,
    notyourpostdesc: lang?.notyourpostdesc ?? fallback.notyourpostdesc,
    nowTyping: lang?.nowTyping ?? fallback.nowTyping,
    placeholderAuthor: lang?.placeholderAuthor ?? fallback.placeholderAuthor,
    placeholderContent: lang?.placeholderContent ?? fallback.placeholderContent,
    placeholderTag: lang?.placeholderTag ?? fallback.placeholderTag,
    placeholderTitle: lang?.placeholderTitle ?? fallback.placeholderTitle,
    poll: lang?.poll ?? fallback.poll,
    postcontent: lang?.postcontent ?? fallback.postcontent,
    preview: lang?.preview ?? fallback.preview,
    save: lang?.save ?? fallback.save,
    saved: lang?.saved ?? fallback.saved,
    title: lang?.title ?? fallback.title,
    uploadedcompl: lang?.uploadedcompl ?? fallback.uploadedcompl,
    uploading: lang?.uploading ?? fallback.uploading,
    video: lang?.video ?? fallback.video,
    waituntillphotouploaded: lang?.waituntillphotouploaded ?? fallback.waituntillphotouploaded,
    frommyname: lang?.frommyname ?? fallback.frommyname,
    newpost: lang?.newpost ?? fallback.newpost,
    photosPlaceholder: lang?.photosPlaceholder ?? fallback.photosPlaceholder,
    publicpost: lang?.publicpost ?? fallback.publicpost,
  };
}
