'use client';

import React, { useRef, useEffect, useCallback, useState } from 'react';
import { cn, SvgIcon } from '../feed/editor-shared';
import { parsePostContentToHtml } from './post-parser';
import Modal from './modal';
type RichTextEditorProps = {
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  className?: string;
};

function htmlToBBCode(html: string): string {
  if (typeof window === 'undefined') return html;

  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');

  function processNode(node: Node): string {
    if (node.nodeType === Node.TEXT_NODE) {
      return node.textContent || '';
    }
    if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node as HTMLElement;
      const tagName = el.tagName.toLowerCase();

      if (tagName === 'br') return '\n';

      let inner = '';
      for (let i = 0; i < el.childNodes.length; i++) {
        inner += processNode(el.childNodes[i]);
      }

      if (tagName === 'b' || tagName === 'strong') return `[b]${inner}[/b]`;
      if (tagName === 'i' || tagName === 'em') return `[i]${inner}[/i]`;
      if (tagName === 's' || tagName === 'strike') return `[s]${inner}[/s]`;
      if (tagName === 'a') {
        let href = (el as HTMLAnchorElement).getAttribute('href') || '';
        if (href.includes('redirect?link=')) {
          try { href = decodeURIComponent(href.split('redirect?link=')[1]); } catch (e) { }
        }
        return `[${href}|${inner}]`;
      }
      if (tagName === 'div' || tagName === 'p') {
        if (inner === '\n') return '\n';
        return inner !== '' ? '\n' + inner : '\n';
      }

      return inner;
    }
    return '';
  }

  let result = '';
  for (let i = 0; i < doc.body.childNodes.length; i++) {
    result += processNode(doc.body.childNodes[i]);
  }

  // Trim leading/trailing newlines that might be generated by block elements
  return result.replace(/^[\n\r]+|[\n\r]+$/g, '');
}

export default function RichTextEditor({ value, onChange, placeholder, className }: RichTextEditorProps) {
  const editorRef = useRef<HTMLDivElement>(null);
  const isUpdatingRef = useRef(false);
  const [isEmpty, setIsEmpty] = useState(!value);
  const [activeFormats, setActiveFormats] = useState({ bold: false, italic: false, strikeThrough: false, link: false });

  const [isLinkModalOpen, setIsLinkModalOpen] = useState(false);
  const [linkUrl, setLinkUrl] = useState('');
  const [linkText, setLinkText] = useState('');
  const [savedRange, setSavedRange] = useState<Range | null>(null);

  // Set default paragraph separator to <br> to avoid <div> nesting issues
  useEffect(() => {
    document.execCommand('defaultParagraphSeparator', false, 'br');
  }, []);

  useEffect(() => {
    if (editorRef.current && !isUpdatingRef.current && value !== undefined) {
      const div = editorRef.current;
      const parsedHtml = parsePostContentToHtml(value, true);
      if (div.innerHTML !== parsedHtml) {
        editorRef.current.innerHTML = parsedHtml;
        setIsEmpty(!value || !editorRef.current.textContent?.trim());
      }
    }
  }, [value]);

  const updateActiveFormats = useCallback(() => {
    if (!editorRef.current) return;
    setActiveFormats({
      bold: document.queryCommandState('bold'),
      italic: document.queryCommandState('italic'),
      strikeThrough: document.queryCommandState('strikeThrough'),
      link: !!window.getSelection()?.focusNode?.parentElement?.closest('a')
    });
  }, []);

  const handleInput = useCallback(() => {
    if (!editorRef.current) return;

    isUpdatingRef.current = true;
    const html = editorRef.current.innerHTML;
    const bbcode = htmlToBBCode(html);

    onChange(bbcode);
    setIsEmpty(!bbcode || !editorRef.current.textContent?.trim());
    updateActiveFormats();

    setTimeout(() => {
      isUpdatingRef.current = false;
    }, 0);
  }, [onChange, updateActiveFormats]);

  const execCommand = (command: string, arg?: string) => {
    document.execCommand(command, false, arg);
    editorRef.current?.focus();
    handleInput();
    updateActiveFormats();
  };

  const handleLink = () => {
    const selection = window.getSelection();
    let parentA: HTMLAnchorElement | null = null;
    let initialUrl = '';
    let initialText = '';
    let targetRange: Range | null = null;

    if (selection && selection.rangeCount > 0) {
      if (editorRef.current?.contains(selection.anchorNode)) {
        targetRange = selection.getRangeAt(0);
        
        let node: Node | null = selection.anchorNode;
        while (node && node !== editorRef.current) {
          if (node.nodeName === 'A') {
            parentA = node as HTMLAnchorElement;
            break;
          }
          node = node.parentNode;
        }

        if (parentA) {
          initialText = parentA.textContent || '';
          
          let href = parentA.getAttribute('href') || '';
          if (href.includes('redirect?link=')) {
            try {
              const urlObj = new URL(href);
              const linkParam = urlObj.searchParams.get('link');
              if (linkParam) {
                href = linkParam;
              }
            } catch (e) {
              // Ignore invalid url
            }
          }
          initialUrl = href;
          
          targetRange = document.createRange();
          targetRange.selectNode(parentA);
        } else {
          initialText = selection.toString();
        }
      }
    }
    
    setSavedRange(targetRange);
    setLinkText(initialText);
    setLinkUrl(initialUrl);
    setIsLinkModalOpen(true);
  };

  const handleSubmitLink = (e: React.FormEvent) => {
    e.preventDefault();
    setIsLinkModalOpen(false);

    const url = linkUrl.trim();
    if (!url) return;

    const text = linkText.trim() || url;

    // Restore selection if any
    if (savedRange) {
      const selection = window.getSelection();
      if (selection) {
        selection.removeAllRanges();
        selection.addRange(savedRange);
      }
    } else {
      // Focus at the end if no saved range
      editorRef.current?.focus();
    }

    const a = document.createElement('a');
    let finalUrl = url;
    if (!/^https?:\/\//i.test(finalUrl)) {
      finalUrl = 'https://' + finalUrl;
    }
    a.href = finalUrl;
    a.textContent = text;

    document.execCommand('insertHTML', false, a.outerHTML);
    handleInput();
    updateActiveFormats();
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === ' ' || e.key === 'Enter') {
      const selection = window.getSelection();
      if (!selection || selection.rangeCount === 0 || !selection.isCollapsed) return;

      const node = selection.focusNode;
      if (!node || node.nodeType !== Node.TEXT_NODE) return;
      if (node.parentElement?.closest('a')) return;

      const offset = selection.focusOffset;
      const textBeforeCaret = node.textContent?.slice(0, offset) || '';

      const AUTO_LINK_REGEX = /([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}|(?:https?:\/\/)?(?:[a-zA-Z0-9\-а-яА-ЯёЁ]+\.)+[a-zA-Zа-яА-ЯёЁ]{2,20}(?:\/[^\s<]*[^<.,:;"')\]\s]|\/)?)$/u;
      
      const match = textBeforeCaret.match(AUTO_LINK_REGEX);
      if (match && match[0]) {
        e.preventDefault();
        const url = match[0];
        
        const urlStartOffset = textBeforeCaret.lastIndexOf(url);
        
        const range = document.createRange();
        range.setStart(node, urlStartOffset);
        range.setEnd(node, urlStartOffset + url.length);
        
        selection.removeAllRanges();
        selection.addRange(range);
        
        let finalUrl = url;
        if (!/^https?:\/\//i.test(finalUrl) && !finalUrl.includes('@')) {
            finalUrl = 'https://' + finalUrl;
        } else if (finalUrl.includes('@') && !finalUrl.startsWith('mailto:')) {
            finalUrl = 'mailto:' + finalUrl;
        }

        document.execCommand('createLink', false, finalUrl);
        
        selection.collapseToEnd();
        
        const aNode = selection.focusNode?.parentElement?.closest('a');
        if (aNode) {
            const temp = document.createTextNode('\u200B');
            aNode.parentNode?.insertBefore(temp, aNode.nextSibling);
            selection.collapse(temp, 1);
        }
        
        if (e.key === 'Enter') {
            document.execCommand('insertLineBreak');
        } else {
            document.execCommand('insertText', false, ' ');
        }
        
        handleInput();
      }
    }
  };

  return (
    <div className={cn("flex flex-col w-full relative", className)}>
      <div className="flex items-center gap-1.5 p-1.5">
        <button
          type="button"
          onClick={() => execCommand('bold')}
          className={cn(
            "flex justify-center items-center cursor-pointer rounded-3xl h-7 w-7 border shadow duration-300 active:scale-95",
            activeFormats.bold 
              ? "bg-zinc-200 text-zinc-900 border-zinc-300" 
              : "bg-zinc-900 hover:bg-zinc-700 text-white border-zinc-600/30 text-zinc-400"
          )}
          title="Жирный"
        >
          B
        </button>
        <button
          type="button"
          onClick={() => execCommand('italic')}
          className={cn(
            "flex justify-center items-center cursor-pointer rounded-3xl h-7 w-7 border shadow duration-300 active:scale-95 italic font-serif",
            activeFormats.italic 
              ? "bg-zinc-200 text-zinc-900 border-zinc-300" 
              : "bg-zinc-900 hover:bg-zinc-700 text-white border-zinc-600/30 text-zinc-400"
          )}
          title="Курсив"
        >
          I
        </button>
        <button
          type="button"
          onClick={() => execCommand('strikeThrough')}
          className={cn(
            "flex justify-center items-center cursor-pointer rounded-3xl h-7 w-7 border shadow duration-300 active:scale-95 line-through",
            activeFormats.strikeThrough 
              ? "bg-zinc-200 text-zinc-900 border-zinc-300" 
              : "bg-zinc-900 hover:bg-zinc-700 text-white border-zinc-600/30 text-zinc-400"
          )}
          title="Зачёркнутый"
        >
          S
        </button>
        <div className="w-[1px] h-4 bg-zinc-600/50 mx-1" />
        <button
          type="button"
          onClick={handleLink}
          className={cn(
            "flex justify-center items-center cursor-pointer rounded-3xl h-7 w-7 border shadow duration-300 active:scale-95",
            activeFormats.link 
              ? "bg-zinc-200 text-zinc-900 border-zinc-300" 
              : "bg-zinc-900 hover:bg-zinc-700 text-white border-zinc-600/30 text-zinc-400"
          )}
          title="Вставить ссылку"
        >
          <SvgIcon className="w-5 h-5 fill-current" id="IC-link" />
        </button>
      </div>

      <div className="relative">
        {isEmpty && placeholder && (
          <div className="absolute top-3 left-3 text-zinc-500 pointer-events-none whitespace-pre-wrap">
            {placeholder}
          </div>
        )}
        <div
          ref={editorRef}
          contentEditable
          onInput={handleInput}
          onBlur={handleInput}
          onKeyDown={handleKeyDown}
          onMouseUp={updateActiveFormats}
          onKeyUp={updateActiveFormats}
          className="bg-transparent p-3 w-full text-white min-h-[8rem] max-h-96 overflow-y-auto focus:outline-none duration-300 whitespace-pre-wrap break-words rounded-b-3xl [&_a]:text-purple-500 [&_a]:hover:text-purple-600 [&_a]:duration-300"
          style={{ userSelect: 'text' }}
        />
      </div>

      <Modal
        isOpen={isLinkModalOpen}
        onClose={() => setIsLinkModalOpen(false)}
        title="Вставить ссылку"
      >
        <form onSubmit={handleSubmitLink} className="flex flex-col gap-3">
          <div className="flex flex-col w-full text-left">
            <span className="text-zinc-400 pl-4 z-20 -mt-1.5 text-sm">Текст ссылки (если пусто — сама ссылка)</span>
            <div className="flex bg-zinc-800/90 rounded-full w-full p-1 h-12 -mt-3 z-10 border border-zinc-600/30">
              <input
                type="text"
                autoFocus
                className="bg-transparent w-full focus:ring-0 focus:outline-0 focus:border-0 pl-2 text-white"
                placeholder="Текст для отображения"
                value={linkText}
                onChange={(e) => setLinkText(e.target.value)}
              />
            </div>
          </div>
          
          <div className="flex flex-col w-full text-left mt-2">
            <span className="text-zinc-400 pl-4 z-20 -mt-1.5 text-sm">URL</span>
            <div className="flex bg-zinc-800/90 rounded-full w-full p-1 h-12 -mt-3 z-10 border border-zinc-600/30">
              <input
                type="url"
                required
                className="bg-transparent w-full focus:ring-0 focus:outline-0 focus:border-0 pl-2 text-white"
                placeholder="https://google.com"
                value={linkUrl}
                onChange={(e) => setLinkUrl(e.target.value)}
              />
            </div>
          </div>

          <button
            type="submit"
            className="w-full flex items-center justify-center gap-3 px-4 py-3 text-lg duration-300 active:scale-95 bg-purple-700 hover:bg-purple-600 disabled:bg-zinc-800 disabled:text-zinc-500 text-zinc-100 rounded-3xl shadow cursor-pointer font-bold mt-2"
          >
            Вставить
          </button>
        </form>
      </Modal>
    </div>
  );
}
