'use client';

import React, { useRef, useEffect, useCallback, useState } from 'react';
import { cn, SvgIcon } from '../feed/editor-shared';
import { parsePostContentToHtml } from './post-parser';

type RichTextEditorProps = {
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  className?: string;
};

function htmlToBBCode(html: string): string {
  if (typeof window === 'undefined') return html;

  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');

  function processNode(node: Node): string {
    if (node.nodeType === Node.TEXT_NODE) {
      return node.textContent || '';
    }
    if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node as HTMLElement;
      const tagName = el.tagName.toLowerCase();

      if (tagName === 'br') return '\n';

      let inner = '';
      for (let i = 0; i < el.childNodes.length; i++) {
        inner += processNode(el.childNodes[i]);
      }

      if (tagName === 'b' || tagName === 'strong') return `[b]${inner}[/b]`;
      if (tagName === 'i' || tagName === 'em') return `[i]${inner}[/i]`;
      if (tagName === 's' || tagName === 'strike') return `[s]${inner}[/s]`;
      if (tagName === 'a') {
        let href = (el as HTMLAnchorElement).getAttribute('href') || '';
        if (href.includes('redirect?link=')) {
          try { href = decodeURIComponent(href.split('redirect?link=')[1]); } catch (e) { }
        }
        return `[${href}|${inner}]`;
      }
      if (tagName === 'div' || tagName === 'p') {
        if (inner === '\n') return '\n';
        return inner !== '' ? inner + '\n' : '\n';
      }

      return inner;
    }
    return '';
  }

  let result = '';
  for (let i = 0; i < doc.body.childNodes.length; i++) {
    result += processNode(doc.body.childNodes[i]);
  }

  // Truncate trailing newlines generated by div wrappers if needed, 
  // but standard browser behaviour with defaultParagraphSeparator='br' minimizes this.
  return result;
}

export default function RichTextEditor({ value, onChange, placeholder, className }: RichTextEditorProps) {
  const editorRef = useRef<HTMLDivElement>(null);
  const isUpdatingRef = useRef(false);
  const [isEmpty, setIsEmpty] = useState(!value);

  // Set default paragraph separator to <br> to avoid <div> nesting issues
  useEffect(() => {
    document.execCommand('defaultParagraphSeparator', false, 'br');
  }, []);

  useEffect(() => {
    if (editorRef.current && !isUpdatingRef.current) {
      const parsedHtml = parsePostContentToHtml(value);
      if (editorRef.current.innerHTML !== parsedHtml) {
        editorRef.current.innerHTML = parsedHtml;
        setIsEmpty(!value || !editorRef.current.textContent?.trim());
      }
    }
  }, [value]);

  const handleInput = useCallback(() => {
    if (!editorRef.current) return;

    isUpdatingRef.current = true;
    const html = editorRef.current.innerHTML;
    const bbcode = htmlToBBCode(html);

    onChange(bbcode);
    setIsEmpty(!bbcode || !editorRef.current.textContent?.trim());

    setTimeout(() => {
      isUpdatingRef.current = false;
    }, 0);
  }, [onChange]);

  const execCommand = (command: string, arg?: string) => {
    document.execCommand(command, false, arg);
    editorRef.current?.focus();
    handleInput();
  };

  const handleLink = () => {
    const url = prompt('Введите ссылку (например, https://google.com):');
    if (url) {
      document.execCommand('createLink', false, url);
      editorRef.current?.focus();
      handleInput();
    }
  };

  return (
    <div className={cn("flex flex-col w-full relative", className)}>
      <div className="flex items-center gap-1.5 p-1.5">
        <button
          type="button"
          onClick={() => execCommand('bold')}
          className="flex justify-center items-center cursor-pointer rounded-3xl w-8 h-8 bg-zinc-800/0 hover:bg-zinc-700/80 duration-300 active:scale-95 text-zinc-400 h-7 w-7 border border-zinc-600/30 bg-zinc-900 hover:bg-zinc-700 rounded-3xl shadow text-white"
          title="Жирный"
        >
          B
        </button>
        <button
          type="button"
          onClick={() => execCommand('italic')}
          className="flex justify-center items-center cursor-pointer rounded-3xl w-8 h-8 bg-zinc-800/0 hover:bg-zinc-700/80 duration-300 active:scale-95 text-zinc-400 h-7 w-7 border border-zinc-600/30 bg-zinc-900 hover:bg-zinc-700 rounded-3xl shadow text-white"
          title="Курсив"
        >
          I
        </button>
        <button
          type="button"
          onClick={() => execCommand('strikeThrough')}
          className="flex justify-center items-center cursor-pointer rounded-3xl w-8 h-8 bg-zinc-800/0 hover:bg-zinc-700/80 duration-300 active:scale-95 text-zinc-400 h-7 w-7 border border-zinc-600/30 bg-zinc-900 hover:bg-zinc-700 rounded-3xl shadow text-white"
          title="Зачёркнутый"
        >
          S
        </button>
        <div className="w-[1px] h-4 bg-zinc-600/50 mx-1" />
        <button
          type="button"
          onClick={handleLink}
          className="flex justify-center items-center cursor-pointer rounded-3xl w-8 h-8 bg-zinc-800/0 hover:bg-zinc-700/80 duration-300 active:scale-95 text-zinc-400 h-7 w-7 border border-zinc-600/30 bg-zinc-900 hover:bg-zinc-700 rounded-3xl shadow text-white"
          title="Вставить ссылку"
        >
          <SvgIcon className="w-5 h-5 fill-current" id="IC-link" />
        </button>
      </div>

      <div className="relative">
        {isEmpty && placeholder && (
          <div className="absolute top-3 left-3 text-zinc-500 pointer-events-none whitespace-pre-wrap">
            {placeholder}
          </div>
        )}
        <div
          ref={editorRef}
          contentEditable
          onInput={handleInput}
          onBlur={handleInput}
          className="bg-transparent p-3 w-full text-white min-h-[8rem] max-h-96 overflow-y-auto focus:outline-none duration-300 whitespace-pre-wrap break-words rounded-b-3xl"
          style={{ userSelect: 'text' }}
        />
      </div>
    </div>
  );
}
