import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const pageSource = readFileSync(new URL('./[hash]/page.tsx', import.meta.url), 'utf8');
const clientSource = readFileSync(new URL('./[hash]/group-call-client.tsx', import.meta.url), 'utf8');
const tileSource = readFileSync(new URL('./components/group-call-tile.tsx', import.meta.url), 'utf8');
const ruLocale = readFileSync(new URL('../../locales/ru.ts', import.meta.url), 'utf8');
const enLocale = readFileSync(new URL('../../locales/en.ts', import.meta.url), 'utf8');

assert.doesNotMatch(pageSource, /\bh-screen\b/);
assert.match(pageSource, /min-h-dvh/);
assert.match(clientSource, /min-h-dvh/);
assert.match(clientSource, /safe-area-inset-top/);
assert.match(clientSource, /safe-area-inset-bottom/);
assert.match(clientSource, /focusedParticipantId/);
assert.match(clientSource, /resolveFocusedParticipantId/);
assert.doesNotMatch(clientSource, /visibleParticipants\.filter/);
assert.match(clientSource, /hidden=\{activeFocusedParticipantId !== null/);
assert.match(clientSource, /lang\?\.media_access_desc/);
assert.match(tileSource, /participant\.screen_enabled \? 'object-contain' : 'object-cover'/);
assert.match(tileSource, /voice_focus_video/);
assert.match(tileSource, /voice_return_to_grid/);
assert.match(tileSource, /hasPlayableVideoTrack/);
assert.match(tileSource, /track\.addEventListener\('mute'/);
assert.match(tileSource, /track\.addEventListener\('unmute'/);
assert.match(tileSource, /const attemptPlayback/);
assert.match(tileSource, /video\.addEventListener\('loadedmetadata', attemptPlayback\)/);
assert.match(tileSource, /video\.addEventListener\('canplay', attemptPlayback\)/);
assert.match(tileSource, /document\.addEventListener\('visibilitychange', handleVisibilityChange\)/);
assert.match(tileSource, /attemptPlayback\(\);/);
assert.match(tileSource, /const audioRef = useRef<HTMLAudioElement/);
assert.match(tileSource, /videoOnlyStream = stream \? new MediaStream\(stream\.getVideoTracks\(\)\)/);
assert.match(tileSource, /audioOnlyStream = stream \? new MediaStream\(stream\.getAudioTracks\(\)\)/);
assert.match(tileSource, /<audio ref=\{audioRef\}/);
assert.match(tileSource, /muted\s*$/m);
assert.match(ruLocale, /"voice_focus_video"/);
assert.match(ruLocale, /"voice_return_to_grid"/);
assert.match(enLocale, /"voice_focus_video"/);
assert.match(enLocale, /"voice_return_to_grid"/);
assert.match(clientSource, /availableCameras\.map/);
assert.match(clientSource, /ScreenIcon active=/);
assert.match(clientSource, /SpeakerIcon off=/);

const hookSource = readFileSync(new URL('./[hash]/use-group-call.ts', import.meta.url), 'utf8');
assert.match(hookSource, /signalQueuesRef/);
assert.match(hookSource, /recoveryTimersRef/);
assert.match(hookSource, /videoWatchdogsRef/);
assert.match(hookSource, /kind: 'restart'/);
assert.match(hookSource, /isGroupCallOfferer/);
assert.match(hookSource, /resolveOfferCollision/);
assert.match(hookSource, /onnegotiationneeded/);
assert.match(hookSource, /Promise\.allSettled/);
assert.doesNotMatch(hookSource, /readOutboundVideoBytes/);
assert.doesNotMatch(hookSource, /outboundVideoWatchdogsRef/);
assert.match(hookSource, /video: true/);
assert.match(hookSource, /cameraTrackRef\.current = stream\.getVideoTracks\(\)\[0\]/);
assert.match(hookSource, /activeVideoTrackRef\.current = cameraTrackRef\.current/);
assert.match(hookSource, /peer\.addTrack\(activeVideoTrack, mediaStream\)/);
assert.match(hookSource, /videoSendersRef\.current\.set\(targetUserId, videoSender\)/);
assert.doesNotMatch(hookSource, /addTransceiver\('video', \{\s*direction: 'sendrecv'/);

console.log('group call layout: ok');
